#pragma once

using namespace ATL;

template <class T>
class CProxy_IShapeCtlEvents : public IConnectionPointImpl<T, &__uuidof(_IShapeCtlEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
